### ISSUE TITLE
shell while loop not working

### ISSUE THREAD

**Issue by ranceforhiwd** [bgaines36/jenkins-pipeline-#3]
I tried to test your script with no luck. The while line is giving errors. Check out this link for an example I found that works with two inner loops.

https://www.tutorialspoint.com/unix/unix-shell-loops.htm

**Comment by bgaines36** [comment]
I got it to work after i changed the auto-increment syntax ..I made the fix and changed my directory to the directory created in the script and used the "Ls" command to view the contents of the directory and there you can see the 100 files. I used this link to help me https://linuxize.com/post/bash-increment-decrement-variable/
